project:
  type: website
  output-dir: docs

author: "Adam S. Darwich"
date: "2026-08-06"

website:
  title: "Statistics for Medical Engineers"

  sidebar:
    search: true
    contents:
      - index.qmd
      - part_01.qmd
      - part_02.qmd
      - part_03.qmd
      - summary.qmd
      - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
