project:
  type: website
  output-dir: docs

website:
  title: "Statistics for Medical Engineers"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Part1"
        href: part_01.qmd
        contents:
          - href: summary.qmd
          - href: references.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  