# Preface {.unnumbered}

First of all, welcome to the Statistics for Medical Engineering course. I hope you will enjoy the course. I have taught on this course since 2021 when it was first designed for the new MSc in Medical Engineering and since last year, 2025, I am the course lead and examiner.

When I took over the course, I had several ideas on how to modernise the content its delivery, there has therefore been a lot of changes to the content during the past year and half or so. The biggest change is that all lectures are now delivered as short video recordings on Canvas. My idea was to give our face-to-face time in class the care and attention it deserves, rather than you listening to me for two hours straight you will do hands-on practicals in R, discuss concepts and solutions with your peers and me. A side effect of this is that a lot of the material has been moved to video recordings. Last year some of the students expressed a desire for written study material beyond the recommended reading list. I therefore decided to create the document you are now reading. I first had an idea that I could collate all the course material and let AI draft chapters, this turned out to be not very good. I therefore decided to work off of the video transcripts, reviewing and revising these manually. 

This is not a course book in statistics, I am not attempting to reinvent the wheel. You are still required to read the recommended reading, best way to look at this material is as a set of notes to help you revise the content of the lectures. I hope you will find this content useful. Saying that, this is a first draft and I have many ideas on how to improve it further in the future. If you have any thoughts on the content, feel free to let me know by email, during class or if you bump into me on campus. 
